# Generated by Django 5.0 on 2024-01-14 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataTune', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadeddata',
            old_name='upload_date',
            new_name='uploaded_at',
        ),
    ]
