# Generated by Django 5.0 on 2023-12-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapp',
            name='Image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
